### ISSUE TITLE
Prueba de como agregar issue

### ISSUE THREAD

**Issue by iavh** [Sjorge667/Jako#1]

**Comment by iavh** [comment]
Hay que suhnir las historias del ultimo catalogo super cool

**Comment by Sjorge667** [comment]
holaa

**Comment by iavh** [comment]
# Hola sofi


![Image](https://user-images.githubusercontent.com/101269946/202497161-b1be850f-b259-4a49-a7ce-30bc2cbdb9e2.png)

- [x] Algo por hacer
